-- 重置数据库：清空所有表内容，保留表结构

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Enroll_isOpen;
TRUNCATE TABLE Course_isOpen;
TRUNCATE TABLE Curricular_isOpen;
TRUNCATE TABLE Msg_Receive;
TRUNCATE TABLE Msg_Send;
TRUNCATE TABLE Take_Exam;
TRUNCATE TABLE Invigilate;
TRUNCATE TABLE Arrange_Exam;
TRUNCATE TABLE Setup_Exam;
TRUNCATE TABLE Arrange_Course;
TRUNCATE TABLE SetupCo_DofW;
TRUNCATE TABLE SetupCo_Prof;
TRUNCATE TABLE Setup_Course;
TRUNCATE TABLE Enrollment;
TRUNCATE TABLE Pursuit;
TRUNCATE TABLE Prerequisite;
TRUNCATE TABLE Prerequisite_temp;
TRUNCATE TABLE TP_Curricular;
TRUNCATE TABLE Setup_Curricular_P;
TRUNCATE TABLE Setup_Curricular_G;
TRUNCATE TABLE Cno_Pool;

TRUNCATE TABLE Message;
TRUNCATE TABLE Exam;
TRUNCATE TABLE Course;
TRUNCATE TABLE Curricular;
TRUNCATE TABLE Other;
TRUNCATE TABLE Univ_Adm;
TRUNCATE TABLE Dept_Adm;
TRUNCATE TABLE Professor;
TRUNCATE TABLE Student;
TRUNCATE TABLE User_Session;
TRUNCATE TABLE User;
TRUNCATE TABLE Date;
TRUNCATE TABLE Classroom;
TRUNCATE TABLE Building;
TRUNCATE TABLE Class;
TRUNCATE TABLE TrainingProgram;
TRUNCATE TABLE Domain;
TRUNCATE TABLE Semester;
TRUNCATE TABLE Lesson;
TRUNCATE TABLE Dayofweek;
TRUNCATE TABLE Campus;
TRUNCATE TABLE Department;

SET FOREIGN_KEY_CHECKS = 1;