-- 销毁数据库：删除所有表
-- 注意：执行前请确保已备份重要数据

SET FOREIGN_KEY_CHECKS = 0;

-- 删除关系表（按依赖关系反向顺序）
DROP TABLE IF EXISTS Enroll_isOpen;
DROP TABLE IF EXISTS Course_isOpen;
DROP TABLE IF EXISTS Curricular_isOpen;
DROP TABLE IF EXISTS Msg_Receive;
DROP TABLE IF EXISTS Msg_Send;
DROP TABLE IF EXISTS Take_Exam;
DROP TABLE IF EXISTS Invigilate;
DROP TABLE IF EXISTS Arrange_Exam;
DROP TABLE IF EXISTS Setup_Exam;
DROP TABLE IF EXISTS Arrange_Course;
DROP TABLE IF EXISTS SetupCo_DofW;
DROP TABLE IF EXISTS SetupCo_Prof;
DROP TABLE IF EXISTS Setup_Course;
DROP TABLE IF EXISTS Enrollment;
DROP TABLE IF EXISTS Pursuit;
DROP TABLE IF EXISTS Prerequisite;
DROP TABLE IF EXISTS TP_Curricular;
DROP TABLE IF EXISTS Setup_Curricular_P;
DROP TABLE IF EXISTS Setup_Curricular_G;
DROP TABLE IF EXISTS Cno_Pool;

-- 删除实体表（按依赖关系反向顺序）
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Exam;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Curricular;
DROP TABLE IF EXISTS Other;
DROP TABLE IF EXISTS Univ_Adm;
DROP TABLE IF EXISTS Dept_Adm;
DROP TABLE IF EXISTS Professor;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Date;
DROP TABLE IF EXISTS Classroom;
DROP TABLE IF EXISTS Building;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS TrainingProgram;
DROP TABLE IF EXISTS Domain;
DROP TABLE IF EXISTS Semester;
DROP TABLE IF EXISTS Lesson;
DROP TABLE IF EXISTS Dayofweek;
DROP TABLE IF EXISTS Campus;
DROP TABLE IF EXISTS Department;

SET FOREIGN_KEY_CHECKS = 1;